export const Greetings = "Hello, I'm Kevin."
export const AboutMe = "a Web Developer based in Rwanda. Currently pursuing a BSc (Hons) in Software Engineering at African Leadership University."

export const NavNames = 'Mboni Kevin.'



// projects
export const ProjectModel = [
    {
        id: "1",
        thumbnail: "",
        title: "Gamezilla",
        liveDemoLink: "/",
        type: "Full-Stack",
        technologies: ["React", "Node JS", "Tailwind CSS", "MongoDB", "Express JS"],
        due: "",
    },
    {
        id: "",
        thumbnail: "",
        title: "",
        liveDemoLink: "/",
        type: "",
        technologies: [""],
        due: "",
    },,
    {
        id: "",
        thumbnail: "",
        title: "",
        liveDemoLink: "/",
        type: "",
        technologies: [""],
        due: "",
    },,
    {
        id: "",
        thumbnail: "",
        title: "",
        liveDemoLink: "/",
        type: "",
        technologies: [""],
        due: "",
    },,
    {
        id: "",
        thumbnail: "",
        title: "",
        liveDemoLink: "/",
        type: "",
        technologies: [""],
        due: "",
    },,
    {
        id: "",
        thumbnail: "",
        title: "",
        liveDemoLink: "/",
        type: "",
        technologies: [""],
        due: "",
    },,
    {
        id: "",
        thumbnail: "",
        title: "",
        liveDemoLink: "/",
        type: "",
        technologies: [""],
        due: "",
    },,
    {
        id: "",
        thumbnail: "",
        title: "",
        liveDemoLink: "/",
        type: "",
        technologies: [""],
        due: "",
    },,
    {
        id: "",
        thumbnail: "",
        title: "",
        liveDemoLink: "/",
        type: "",
        technologies: [""],
        due: "",
    },,
    {
        id: "",
        thumbnail: "",
        title: "",
        liveDemoLink: "/",
        type: "",
        technologies: [""],
        due: "",
    },,
    {
        id: "",
        thumbnail: "",
        title: "",
        liveDemoLink: "/",
        type: "",
        technologies: [""],
        due: "",
    },,
    {
        id: "",
        thumbnail: "",
        title: "",
        liveDemoLink: "/",
        type: "",
        technologies: [""],
        due: "",
    },
]