export const Greetings = "Hello, I'm Kevin."
export const AboutMe = "a Web Developer based in Rwanda. Currently pursuing a BSc (Hons) in Software Engineering at African Leadership University."

export const NavNames = 'Mboni Kevin.'



// projects
export const ProjectModel = [
    {
        id: "1",
        thumbnail: "",
        title: "Gamezilla",
        description: "Online Game Store",
        liveDemoLink: "/",
        type: "Full-Stack",
        technologies: ["MERN Stack", "Tailwind CSS"],
        due: "",
    },
    {
        id: "1",
        thumbnail: "",
        title: "Gamezilla",
        description: "Online Game Store",
        liveDemoLink: "/",
        type: "Full-Stack",
        technologies: ["MERN Stack", "Tailwind CSS"],
        due: "",
    },,
    {
        id: "1",
        thumbnail: "",
        title: "Gamezilla",
        description: "Online Game Store",
        liveDemoLink: "/",
        type: "Full-Stack",
        technologies: ["MERN Stack", "Tailwind CSS"],
        due: "",
    },,
    {
        id: "1",
        thumbnail: "",
        title: "Gamezilla",
        description: "Online Game Store",
        liveDemoLink: "/",
        type: "Full-Stack",
        technologies: ["MERN Stack", "Tailwind CSS"],
        due: "",
    },,
    {
        id: "1",
        thumbnail: "",
        title: "Gamezilla",
        description: "Online Game Store",
        liveDemoLink: "/",
        type: "Full-Stack",
        technologies: ["MERN Stack", "Tailwind CSS"],
        due: "",
    },,
    {
        id: "1",
        thumbnail: "",
        title: "Gamezilla",
        description: "Online Game Store",
        liveDemoLink: "/",
        type: "Full-Stack",
        technologies: ["MERN Stack", "Tailwind CSS"],
        due: "",
    },,
    {
        id: "1",
        thumbnail: "",
        title: "Gamezilla",
        description: "Online Game Store",
        liveDemoLink: "/",
        type: "Full-Stack",
        technologies: ["MERN Stack", "Tailwind CSS"],
        due: "",
    },,
    {
        id: "1",
        thumbnail: "",
        title: "Gamezilla",
        description: "Online Game Store",
        liveDemoLink: "/",
        type: "Full-Stack",
        technologies: ["MERN Stack", "Tailwind CSS"],
        due: "",
    },,
    {
        id: "1",
        thumbnail: "",
        title: "Gamezilla",
        description: "Online Game Store",
        liveDemoLink: "/",
        type: "Full-Stack",
        technologies: ["MERN Stack", "Tailwind CSS"],
        due: "",
    },,
    {
        id: "1",
        thumbnail: "",
        title: "Gamezilla",
        description: "Online Game Store",
        liveDemoLink: "/",
        type: "Full-Stack",
        technologies: ["MERN Stack", "Tailwind CSS"],
        due: "",
    },,
    {
        id: "1",
        thumbnail: "",
        title: "Gamezilla",
        description: "Online Game Store",
        liveDemoLink: "/",
        type: "Full-Stack",
        technologies: ["MERN Stack", "Tailwind CSS"],
        due: "",
    },,
    {
        id: "1",
        thumbnail: "",
        title: "Gamezilla",
        description: "Online Game Store",
        liveDemoLink: "/",
        type: "Full-Stack",
        technologies: ["MERN Stack", "Tailwind CSS"],
        due: "",
    },

    
]